name: Run Discord Bot
on:
  schedule:
    - cron: '25 */6 * * *'
  push:
    branches: [ main ]
  workflow_dispatch:

# This rule cancels any older running versions of the bot automatically!
concurrency:
  group: discord-bot-runtime
  cancel-in-progress: true

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Start Bot
      env:
        TOKEN: ${{ secrets.TOKEN }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        GUILD_ID: ${{ secrets.GUILD_ID }}
      run: node index.js
